# Docker Environment Configuration

spring:
  application:
    name: fix-log-comparison
  
  # Email Configuration for Docker
  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Logging Configuration for Docker
logging:
  level:
    org.example.comparison: INFO
    org.springframework.mail: WARN
    com.jcraft.jsch: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/fix-comparison.log

# Application Specific Configuration for Docker
comparison:
  # Primary Database Configuration
  primary:
    url: jdbc:oracle:thin:@${PRIMARY_DB_HOST:oracle-primary}:${PRIMARY_DB_PORT:1521}:${PRIMARY_DB_SID:XE}
    username: ${PRIMARY_DB_USER}
    password: ${PRIMARY_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  
  # Secondary Database Configuration
  secondary:
    url: jdbc:oracle:thin:@${SECONDARY_DB_HOST:oracle-secondary}:${SECONDARY_DB_PORT:1521}:${SECONDARY_DB_SID:XE}
    username: ${SECONDARY_DB_USER}
    password: ${SECONDARY_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  
  # SFTP Configuration
  sftp:
    host: ${SFTP_HOST:sftp-server}
    port: ${SFTP_PORT:22}
    username: ${SFTP_USER}
    password: ${SFTP_PASSWORD}
    remote-directory: ${SFTP_REMOTE_DIR:/fix_logs}
    connection-timeout: 30000
    session-timeout: 30000
  
  # Email Configuration
  email:
    from: ${EMAIL_FROM:fix-comparison@company.com}
    to:
      - ${EMAIL_TO_1:recipient1@company.com}
      - ${EMAIL_TO_2:recipient2@company.com}
    cc:
      - ${EMAIL_CC_1:cc1@company.com}
    subject: "[DOCKER] Daily FIX EOD Reconciliation Report"
  
  # Report Configuration
  report:
    output-directory: ${REPORT_OUTPUT_DIR:./reports}
    excel-file-name: "docker_fix_comparison_report_{date}.xlsx"
    delete-old-reports: true
    keep-reports-for-days: 30

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  server:
    port: 8080