tds.drtp_endpoints=127.0.0.1:6003,127.0.0.2:6003
vault.secret_path=REPLACE_ME_DEV_SECRET_PATH

smtp.from=tds-reporter-dev@example.com
email.default_to=dev-ops@example.com
email.default_cc=
email.subject=TDS Client Funding and Risk Ratio Report DEV
