tds.drtp_endpoints=10.20.30.40:6003,10.20.30.41:6003
vault.secret_path=REPLACE_ME_PROD_SECRET_PATH

smtp.from=tds-reporter@example.com
email.to=ops@example.com,risk@example.com
email.cc=support@example.com
email.subject=TDS Client Funding and Risk Ratio Report
