tds.drtp_endpoints=${TDS_DRTP_ENDPOINTS:10.20.30.40:6003,10.20.30.41:6003}
vault.secret_path=${VAULT_SECRET_PATH:REPLACE_ME_PROD_SECRET_PATH}

smtp.from=${SMTP_FROM:tds-reporter@example.com}
email.default_to=${EMAIL_TO:ops@example.com,risk@example.com}
email.default_cc=${EMAIL_CC:support@example.com}
email.subject=${EMAIL_SUBJECT:TDS Client Funding and Risk Ratio Report}
