tds.drtp_endpoints=${TDS_DRTP_ENDPOINTS:10.10.20.30:6003,10.10.20.31:6003}
vault.secret_path=${VAULT_SECRET_PATH:REPLACE_ME_QA_SECRET_PATH}

smtp.from=${SMTP_FROM:tds-reporter-qa@example.com}
email.default_to=${EMAIL_TO:qa-ops@example.com}
email.default_cc=${EMAIL_CC:risk-qa@example.com}
email.subject=${EMAIL_SUBJECT:TDS Client Funding and Risk Ratio Report QA}
