tds.user=10000
tds.password=
tds.req_timeout_ms=300000
tds.log_level=2000
tds.klg_enable=false
tds.function_no=20100

vault.address=
vault.namespace=
vault.secret_engine=REPLACE_ME_SECRET_ENGINE
vault.secret_key=password

smtp.host=mta-hub.REPLACE_ME.com.cn
smtp.port=2587
smtp.security=starttls
smtp.client_cert_path=/app/.cert/server.pem
smtp.client_key_path=/app/.cert/server.key
smtp.insecure=false
smtp.connect_timeout_seconds=15

report.output_dir=../output
email.template_path=
log.dir=../logs
log.level=info
